export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_ERROR = "GET_PROFILE_ERROR";

export const CLOSE_ERROR_MODAL = "CLOSE_ERROR_MODAL";
export const OPEN_MODAL_CHANGE_PROFILE = "OPEN_MODAL_CHANGE_PROFILE";
export const CLOSE_MODAL_CHANGE_PROFILE = "CLOSE_MODAL_CHANGE_PROFILE";

export const CHANGE_PROFILE = "CHANGE_PROFILE";
export const CHANGE_PROFILE_SUCCESS = "CHANGE_PROFILE_SUCCESS";
export const CHANGE_PROFILE_ERROR = "CHANGE_PROFILE_ERROR";